"""XLSX rendering.

One worksheet per section, plus a cover sheet, so each analysis stays a real
table that can be sorted, filtered and charted. Numbers are written as numbers
rather than formatted strings - that is the whole point of choosing this format
over CSV or PDF.

Uses openpyxl, which the project already depends on for reading uploads.
"""

from __future__ import annotations

import io
import re

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from app.schemas.report import ReportData, ReportSection

CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

#: Excel forbids these in a sheet name and caps it at 31 characters.
_INVALID_SHEET_CHARS = re.compile(r"[\[\]:*?/\\]")
_MAX_SHEET_NAME = 31
#: Excel refuses to open a workbook with an over-long cell string.
_MAX_CELL_TEXT = 32000
_MAX_COLUMN_WIDTH = 60

_HEADER_FILL = PatternFill("solid", fgColor="1F3864")
_HEADER_FONT = Font(color="FFFFFF", bold=True)
_TITLE_FONT = Font(size=14, bold=True)
_LABEL_FONT = Font(bold=True)


def _sheet_name(title: str, used: set[str]) -> str:
    """A valid, unique worksheet name."""
    base = _INVALID_SHEET_CHARS.sub(" ", title).strip()[:_MAX_SHEET_NAME] or "Section"
    name = base
    suffix = 2
    while name.lower() in used:
        tail = f" {suffix}"
        name = f"{base[: _MAX_SHEET_NAME - len(tail)]}{tail}"
        suffix += 1
    used.add(name.lower())
    return name


def _write(sheet: Worksheet, row: int, values: list[object]) -> int:
    """Write one row, keeping numbers numeric and clamping long text."""
    for index, value in enumerate(values, start=1):
        cell = sheet.cell(row=row, column=index)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            cell.value = value
        elif value is None:
            cell.value = None
        else:
            cell.value = str(value)[:_MAX_CELL_TEXT]
    return row + 1


def _autosize(sheet: Worksheet) -> None:
    for column in sheet.columns:
        longest = max(
            (len(str(cell.value)) for cell in column if cell.value is not None), default=0
        )
        letter = get_column_letter(column[0].column)
        sheet.column_dimensions[letter].width = min(max(longest + 2, 10), _MAX_COLUMN_WIDTH)


def _cover(sheet: Worksheet, data: ReportData) -> None:
    row = 1
    sheet.cell(row=row, column=1, value=data.title).font = _TITLE_FONT
    row += 1
    if data.subtitle:
        row = _write(sheet, row, [data.subtitle])
    row += 1

    facts: list[tuple[str, object]] = [
        ("Dataset", data.dataset_name),
        ("Source", data.version_label),
        ("Template", data.template.value),
        ("Rows", data.row_count),
        ("Columns", data.column_count),
        ("Generated at", data.generated_at.isoformat()),
        ("Generated by", data.generated_by),
        ("AI narrative", "included" if data.ai_available else (data.ai_status or "not included")),
    ]
    for label, value in facts:
        sheet.cell(row=row, column=1, value=label).font = _LABEL_FONT
        row = _write(sheet, row, [label, value])

    row += 1
    sheet.cell(row=row, column=1, value="Sections in this report").font = _LABEL_FONT
    row += 1
    for section in data.sections:
        row = _write(sheet, row, [section.title])

    if data.skipped:
        row += 1
        sheet.cell(row=row, column=1, value="Sections not included").font = _LABEL_FONT
        row += 1
        row = _write(sheet, row, ["Section", "Reason"])
        for item in data.skipped:
            row = _write(sheet, row, [item["section"], item["reason"]])

    _autosize(sheet)


def _section(sheet: Worksheet, section: ReportSection) -> None:
    row = 1
    sheet.cell(row=row, column=1, value=section.title).font = _TITLE_FONT
    row += 2

    if section.unavailable_reason:
        row = _write(sheet, row, ["Not available", section.unavailable_reason])
        row += 1

    for paragraph in section.narrative:
        cell = sheet.cell(row=row, column=1, value=paragraph[:_MAX_CELL_TEXT])
        cell.alignment = Alignment(wrap_text=False)
        row += 1
    if section.narrative:
        row += 1

    if section.metrics:
        header = row
        row = _write(sheet, row, ["Metric", "Value", "Detail"])
        for index in range(1, 4):
            cell = sheet.cell(row=header, column=index)
            cell.fill = _HEADER_FILL
            cell.font = _HEADER_FONT
        for metric in section.metrics:
            row = _write(sheet, row, [metric.label, metric.value, metric.detail or ""])
        row += 1

    for table in section.tables:
        if table.title:
            sheet.cell(row=row, column=1, value=table.title).font = _LABEL_FONT
            row += 1
        header = row
        row = _write(sheet, row, list(table.columns))
        for index in range(1, len(table.columns) + 1):
            cell = sheet.cell(row=header, column=index)
            cell.fill = _HEADER_FILL
            cell.font = _HEADER_FONT
        for values in table.rows:
            row = _write(sheet, row, list(values))
        if table.note:
            row = _write(sheet, row, [table.note])
        row += 1

    for bullet in section.bullets:
        row = _write(sheet, row, [f"- {bullet}"])

    _autosize(sheet)


def render(data: ReportData) -> bytes:
    """Render the report as a multi-sheet workbook."""
    workbook = Workbook()
    # openpyxl always creates one sheet; the fallback keeps the type honest.
    cover = workbook.active or workbook.create_sheet()
    cover.title = "Report"
    _cover(cover, data)

    used = {"report"}
    for section in data.sections:
        _section(workbook.create_sheet(_sheet_name(section.title, used)), section)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()
